--!strict
local ItemId = require(script.Parent.Parent.Parent.Types.ItemId)
local Rarity = require(script.Parent.Parent.Parent.Types.Rarity)
local Category = require(script.Parent.Parent.Parent.Types.Category)
local ItemData = require(script.Parent.Parent.Parent.Types.ItemData)
local ShopItemUnlock = require(script.Parent.Parent.ShopItemUnlock)

local slice: { [string]: ItemData.ItemData } = {
	[ItemId.IronOre] = {
		id = ItemId.IronOre,
		name = "Iron Ore",
		description = "Raw iron ore extracted from mines. Can be smelted into iron plates.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 15,
		SellPrice = 7,
		Unlock = ShopItemUnlock.chapter1BasicShopItemUnlock(),
	},

	[ItemId.CopperOre] = {
		id = ItemId.CopperOre,
		name = "Copper Ore",
		description = "Raw copper ore. Essential for crafting electronic components.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 15,
		SellPrice = 7,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Stone] = {
		id = ItemId.Stone,
		name = "Stone",
		description = "Basic stone material. Common and versatile for construction.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 10,
		SellPrice = 5,
	},

	[ItemId.CopperPlate] = {
		id = ItemId.CopperPlate,
		name = "Copper Plate",
		description = "A refined copper plate smelted from raw ore.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 30,
		SellPrice = 15,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.IronPlate] = {
		id = ItemId.IronPlate,
		name = "Iron Plate",
		description = "A refined iron plate smelted from ore and coal.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 35,
		SellPrice = 17,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Coal] = {
		id = ItemId.Coal,
		name = "Coal",
		description = "Dark mineral used as fuel in smelting and forging.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 12,
		SellPrice = 6,
	},

	[ItemId.Charcoal] = {
		id = ItemId.Charcoal,
		name = "Charcoal",
		description = "Charred wood used as fuel in machine processing.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = nil,
		SellPrice = 5,
	},

	-- New Raw Materials
	[ItemId.GoldOre] = {
		id = ItemId.GoldOre,
		name = "Gold Ore",
		description = "Precious gold ore found deep in the mines.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 40,
		SellPrice = 20,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Crystal] = {
		id = ItemId.Crystal,
		name = "Crystal",
		description = "A shimmering crystal pulsing with latent magical energy.",
		icon = "rbxassetid://0",
		rarity = Rarity.Rare,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 50,
		BuyPrice = 60,
		SellPrice = 30,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Herb] = {
		id = ItemId.Herb,
		name = "Herb",
		description = "A fragrant herb with restorative properties.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 8,
		SellPrice = 4,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Silk] = {
		id = ItemId.Silk,
		name = "Silk",
		description = "Fine spider silk harvested from cave dwellers.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 25,
		SellPrice = 12,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	-- New Refined Materials
	[ItemId.SteelPlate] = {
		id = ItemId.SteelPlate,
		name = "Steel Plate",
		description = "Tempered steel plate, superior to iron in every way.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = 70,
		SellPrice = 35,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.GoldPlate] = {
		id = ItemId.GoldPlate,
		name = "Gold Plate",
		description = "A gleaming plate of refined gold.",
		icon = "rbxassetid://0",
		rarity = Rarity.Rare,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 50,
		BuyPrice = 100,
		SellPrice = 50,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.DragonScale] = {
		id = ItemId.DragonScale,
		name = "Dragon Scale",
		description = "An impossibly tough scale shed by an ancient dragon.",
		icon = "rbxassetid://0",
		rarity = Rarity.Epic,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 25,
		BuyPrice = 250,
		SellPrice = 125,
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	-- Materials - Wood
	[ItemId.Wood] = {
		id = ItemId.Wood,
		name = "Wood",
		description = "Common oak wood, useful for basic crafting.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = nil,
		SellPrice = 2,
	},
	[ItemId.Timber] = {
		id = ItemId.Timber,
		name = "Timber",
		description = "Pine timber, sturdy and reliable.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = nil,
		SellPrice = 4,
	},
	[ItemId.Plank] = {
		id = ItemId.Plank,
		name = "Plank",
		description = "Smooth birch plank, good for fine woodworking.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = nil,
		SellPrice = 6,
	},
	[ItemId.Hardwood] = {
		id = ItemId.Hardwood,
		name = "Hardwood",
		description = "Dense mahogany hardwood, prized for high-quality crafts.",
		icon = "rbxassetid://0",
		rarity = Rarity.Rare,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = nil,
		SellPrice = 15,
	},
	[ItemId.WillowWood] = {
		id = ItemId.WillowWood,
		name = "Willow Wood",
		description = "Flexible willow wood, valued for its unique properties.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Material,
		stats = nil,
		stackable = true,
		maxStack = 100,
		BuyPrice = nil,
		SellPrice = 8,
	},

	[ItemId.None] = {
		id = ItemId.None,
		name = "Empty Slot",
		description = "An empty inventory slot.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Material,
		stats = nil,
		stackable = false,
		maxStack = 0,
		BuyPrice = nil,
		SellPrice = nil,
	},
}

return slice

