--!strict
local ItemId = require(script.Parent.Parent.Parent.Types.ItemId)
local Rarity = require(script.Parent.Parent.Parent.Types.Rarity)
local Category = require(script.Parent.Parent.Parent.Types.Category)
local ItemData = require(script.Parent.Parent.Parent.Types.ItemData)
local ShopItemUnlock = require(script.Parent.Parent.ShopItemUnlock)

local slice: { [string]: ItemData.ItemData } = {
	[ItemId.WoodenSword] = {
		id = ItemId.WoodenSword,
		name = "Wooden Sword",
		description = "A basic training sword carved from wood.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Weapon,
		stats = { STR = 2 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 20,
		SellPrice = 10,
		WeaponType = "Sword",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.IronSword] = {
		id = ItemId.IronSword,
		name = "Iron Sword",
		description = "A sturdy sword forged from iron ore.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Weapon,
		stats = { STR = 5 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 50,
		SellPrice = 25,
		WeaponType = "Sword",
		Unlock = ShopItemUnlock.chapter2IronGearUnlock(),
	},

	[ItemId.SteelSword] = {
		id = ItemId.SteelSword,
		name = "Steel Sword",
		description = "A finely crafted sword of tempered steel.",
		icon = "rbxassetid://0",
		rarity = Rarity.Rare,
		category = Category.Weapon,
		stats = { STR = 10 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 120,
		SellPrice = 60,
		WeaponType = "Sword",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.MagicStaff] = {
		id = ItemId.MagicStaff,
		name = "Magic Staff",
		description = "A staff imbued with arcane energy for ranged attacks.",
		icon = "rbxassetid://0",
		rarity = Rarity.Rare,
		category = Category.Weapon,
		stats = { STR = 7 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 100,
		SellPrice = 50,
		WeaponType = "Staff",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Dagger] = {
		id = ItemId.Dagger,
		name = "Dagger",
		description = "A quick blade favoring speed over reach.",
		icon = "rbxassetid://0",
		rarity = Rarity.Common,
		category = Category.Weapon,
		stats = { STR = 3 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 30,
		SellPrice = 15,
		WeaponType = "Dagger",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	-- Gold Tier Weapons
	[ItemId.GoldSword] = {
		id = ItemId.GoldSword,
		name = "Gold Sword",
		description = "An ornate blade forged from pure gold and steel.",
		icon = "rbxassetid://0",
		rarity = Rarity.Epic,
		category = Category.Weapon,
		stats = { STR = 15 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 300,
		SellPrice = 150,
		WeaponType = "Sword",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.CrystalStaff] = {
		id = ItemId.CrystalStaff,
		name = "Crystal Staff",
		description = "A staff crowned with a focused crystal, amplifying magical power.",
		icon = "rbxassetid://0",
		rarity = Rarity.Epic,
		category = Category.Weapon,
		stats = { STR = 12 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 250,
		SellPrice = 125,
		WeaponType = "Staff",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.SteelDagger] = {
		id = ItemId.SteelDagger,
		name = "Steel Dagger",
		description = "A razor-sharp dagger of tempered steel.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Weapon,
		stats = { STR = 6, SPD = 2 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 65,
		SellPrice = 32,
		WeaponType = "Dagger",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Longbow] = {
		id = ItemId.Longbow,
		name = "Longbow",
		description = "A sturdy bow crafted for long-range precision.",
		icon = "rbxassetid://0",
		rarity = Rarity.Uncommon,
		category = Category.Weapon,
		stats = { STR = 7 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 75,
		SellPrice = 37,
		WeaponType = "Bow",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},

	[ItemId.Warhammer] = {
		id = ItemId.Warhammer,
		name = "Warhammer",
		description = "A massive hammer that trades speed for devastating force.",
		icon = "rbxassetid://0",
		rarity = Rarity.Rare,
		category = Category.Weapon,
		stats = { STR = 14 },
		stackable = false,
		maxStack = 1,
		BuyPrice = 150,
		SellPrice = 75,
		WeaponType = "Hammer",
		Unlock = ShopItemUnlock.futureLockedUnlock(),
	},
}

return slice

