--!strict

--[=[
    @class EnemyECSReplicationService
    Enemy-context server replication service that specializes the shared ECS
    replication base for enemy entities, binds the context signals transport,
    and registers the enemy surface that should be visible to clients.
    @server
]=]

local ServerStorage = game:GetService("ServerStorage")

local BaseECSReplicationService = require(ServerStorage.Utilities.ECSUtilities.BaseECSReplicationService)

local EnemyECSReplicationService = {}
EnemyECSReplicationService.__index = EnemyECSReplicationService
setmetatable(EnemyECSReplicationService, { __index = BaseECSReplicationService })

--- Creates the enemy replication service.
--- @within EnemyECSReplicationService
--- @return EnemyECSReplicationService -- The new service instance.
function EnemyECSReplicationService.new()
	local self = setmetatable(BaseECSReplicationService.new("Enemy"), EnemyECSReplicationService)
	self._clientSignals = nil
	return self
end

--- Returns the enemy component registry name.
--- @within EnemyECSReplicationService
--- @return string -- The registry name used during initialization.
function EnemyECSReplicationService:_GetComponentRegistryName(): string
	return "EnemyComponentRegistry"
end

--- Returns the enemy entity factory name.
--- @within EnemyECSReplicationService
--- @return string -- The factory name used during initialization.
function EnemyECSReplicationService:_GetEntityFactoryName(): string
	return "EnemyEntityFactory"
end

--- Resolves the client signal transport needed for enemy replication.
--- @within EnemyECSReplicationService
--- @param registry any -- The context registry.
function EnemyECSReplicationService:_OnInit(registry: any, _name: string)
	self._clientSignals = registry:Get("ClientSignals")
	assert(self._clientSignals ~= nil, "EnemyECSReplicationService: missing ClientSignals")
end

--- Declares the enemy components and tags that should be shared with clients.
--- @within EnemyECSReplicationService
--- @return BaseECSReplicationService.TSharedSchema -- The enemy shared schema.
function EnemyECSReplicationService:_GetSharedSchema()
	local components = self:GetComponentsOrThrow()

	return {
		sharedComponents = {
			components.IdentityComponent,
			components.HealthComponent,
			components.CurrentMoveSpeedComponent,
			components.RoleComponent,
			components.AnimationStateComponent,
			components.AnimationLoopingComponent,
		},
		sharedTags = {
			components.AliveTag,
			components.GoalReachedTag,
		},
	}
end

--- Registers the enemy entities that should be replicated to clients.
--- @within EnemyECSReplicationService
--- @param _registry any -- Unused registry argument from the base hook.
function EnemyECSReplicationService:_RegisterReplicatedSurface(_registry: any)
	for _, entity in ipairs(self:GetEntityFactoryOrThrow():QueryAliveEntities()) do
		self:RegisterEnemyEntity(entity)
	end
end

--- Registers the replicated components and tags for a single enemy entity.
--- @within EnemyECSReplicationService
--- @param entity number -- The ECS entity to expose to clients.
function EnemyECSReplicationService:RegisterEnemyEntity(entity: number)
	local components = self:GetComponentsOrThrow()

	self:RegisterNetworkedEntity(entity)
	self:RegisterReliableComponent(entity, components.IdentityComponent)
	self:RegisterReliableComponent(entity, components.HealthComponent)
	self:RegisterReliableComponent(entity, components.CurrentMoveSpeedComponent)
	self:RegisterReliableComponent(entity, components.RoleComponent)
	self:RegisterReliableComponent(entity, components.AnimationStateComponent)
	self:RegisterReliableComponent(entity, components.AnimationLoopingComponent)
	self:RegisterReliableComponent(entity, components.AliveTag)
	self:RegisterReliableComponent(entity, components.GoalReachedTag)
end

--- Stops replicating a single enemy entity.
--- @within EnemyECSReplicationService
--- @param entity number -- The ECS entity to stop replicating.
function EnemyECSReplicationService:UnregisterEnemyEntity(entity: number)
	self:StopReplicatingEntity(entity)
end

--- Sends the enemy bootstrap payload through the replicated client signals.
--- @within EnemyECSReplicationService
--- @param player Player -- The player receiving the bootstrap payload.
--- @param payload any -- The bootstrap payload generated by the base service.
function EnemyECSReplicationService:_SendBootstrap(player: Player, payload: any)
	self._clientSignals.EnemyBootstrap:Fire(player, payload)
end

--- Sends reliable enemy delta packets through the replicated client signals.
--- @within EnemyECSReplicationService
--- @param player Player -- The player receiving the packet.
--- @param payload any -- The reliable packet payload generated by the base service.
function EnemyECSReplicationService:_SendReliable(player: Player, payload: any)
	self._clientSignals.EnemyReliable:Fire(player, payload)
end

--- Sends unreliable enemy delta packets through the replicated client signals.
--- @within EnemyECSReplicationService
--- @param player Player -- The player receiving the packet.
--- @param payload any -- The unreliable packet payload generated by the base service.
function EnemyECSReplicationService:_SendUnreliable(player: Player, payload: any)
	self._clientSignals.EnemyUnreliable:Fire(player, payload)
end

--- Sends enemy entity-specific packets through the replicated client signals.
--- @within EnemyECSReplicationService
--- @param player Player -- The player receiving the packet.
--- @param payload any -- The entity packet payload generated by the base service.
function EnemyECSReplicationService:_SendEntity(player: Player, payload: any)
	self._clientSignals.EnemyEntity:Fire(player, payload)
end

return EnemyECSReplicationService
