--!strict

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")

local ParallelRunner = require(ServerStorage.Utilities.ParallelRunner)

local FlowSeparationSolveOperation = ParallelRunner.DefineJob({
	Name = "FlowSeparationSolve",
	Version = 1,
	Args = {
		TickId = ParallelRunner.Arg.u32(),
	},
	Results = {
		EntityIndex = ParallelRunner.Result.u32(),
		VelocityX = 0,
		VelocityY = 0,
		TouchedSettledNeighbor = false,
	},
	SharedSchema = {
		Scalars = {
			CellWidthStuds = {},
			OriginX = {},
			OriginY = {},
			WallGridHalfSize = {},
			WallGridWidth = {},
			KForce = {},
			MinSeparationDistance = {},
			WallCollisionEnabled = {},
			WallCollisionAxisClampEnabled = {},
			WallCollisionCornerClampEnabled = {},
			WallCollisionUseUnitRadiusPadding = {},
			WallCollisionCellProbePaddingStuds = {},
			WallCollisionVelocityEpsilon = {},
			ClumpTouchPaddingStuds = {},
		},
		Arrays = {
			WallGrid = {},
		},
	},
	PayloadSchema = {
		EntityCount = ParallelRunner.Arg.u32(),
		DeltaTime = ParallelRunner.Arg.f32(),
		GoalGroupCellRecordStartIndex = { ParallelRunner.Arg.u32() },
		GoalGroupCellRecordCount = { ParallelRunner.Arg.u32() },
		GoalGroupCellHashStartIndex = { ParallelRunner.Arg.u32() },
		GoalGroupCellHashSlotCount = { ParallelRunner.Arg.u32() },
		GoalGroupCellWidthStuds = { ParallelRunner.Arg.f32() },
		GroupCellX = { ParallelRunner.Arg.i32() },
		GroupCellY = { ParallelRunner.Arg.i32() },
		CellPackedKey = { ParallelRunner.Arg.u32() },
		CellMemberStartIndex = { ParallelRunner.Arg.u32() },
		CellMemberCount = { ParallelRunner.Arg.u32() },
		CellMemberEntityIndex = { ParallelRunner.Arg.u32() },
		CellHashPackedKey = { ParallelRunner.Arg.u32() },
		CellHashRecordIndex = { ParallelRunner.Arg.u32() },
		FlatPositionX = { ParallelRunner.Arg.f32() },
		FlatPositionY = { ParallelRunner.Arg.f32() },
		Radius = { ParallelRunner.Arg.f32() },
		FlowVelocityX = { ParallelRunner.Arg.f32() },
		FlowVelocityY = { ParallelRunner.Arg.f32() },
		PreviousVelocityX = { ParallelRunner.Arg.f32() },
		PreviousVelocityY = { ParallelRunner.Arg.f32() },
		WalkSpeed = { ParallelRunner.Arg.f32() },
		VelAlpha = { ParallelRunner.Arg.f32() },
		IsSettled = { ParallelRunner.Arg.boolean() },
	},
	ManagerPayloadSchema = {
		TickId = ParallelRunner.Arg.u32(),
		EntityIds = { ParallelRunner.Arg.u32() },
		GoalKeys = { ParallelRunner.Arg.string16() },
		FlatPositionX = { ParallelRunner.Arg.f32() },
		FlatPositionY = { ParallelRunner.Arg.f32() },
		Radius = { ParallelRunner.Arg.f32() },
		FlowVelocityX = { ParallelRunner.Arg.f32() },
		FlowVelocityY = { ParallelRunner.Arg.f32() },
		PreviousVelocityX = { ParallelRunner.Arg.f32() },
		PreviousVelocityY = { ParallelRunner.Arg.f32() },
		WalkSpeed = { ParallelRunner.Arg.f32() },
		VelAlpha = { ParallelRunner.Arg.f32() },
		IsSettled = { ParallelRunner.Arg.boolean() },
		DeltaTime = ParallelRunner.Arg.f32(),
		CellWidthStuds = ParallelRunner.Arg.f32(),
		OriginX = ParallelRunner.Arg.f32(),
		OriginY = ParallelRunner.Arg.f32(),
		WallGridHalfSize = ParallelRunner.Arg.u32(),
		WallGridWidth = ParallelRunner.Arg.u32(),
		WallGrid = { ParallelRunner.Arg.boolean() },
		KForce = ParallelRunner.Arg.f32(),
		MinSeparationDistance = ParallelRunner.Arg.f32(),
		WallCollisionEnabled = ParallelRunner.Arg.boolean(),
		WallCollisionAxisClampEnabled = ParallelRunner.Arg.boolean(),
		WallCollisionCornerClampEnabled = ParallelRunner.Arg.boolean(),
		WallCollisionUseUnitRadiusPadding = ParallelRunner.Arg.boolean(),
		WallCollisionCellProbePaddingStuds = ParallelRunner.Arg.f32(),
		WallCollisionVelocityEpsilon = ParallelRunner.Arg.f32(),
		ClumpTouchPaddingStuds = ParallelRunner.Arg.f32(),
	},
})

return FlowSeparationSolveOperation
