--!strict

local Errors = table.freeze({
	ILLEGAL_LIFECYCLE_TRANSITION = "Entity lifecycle transition is not allowed",
	INVALID_LIFECYCLE_STATE = "EntityContext method is not allowed in the current lifecycle state",
	DUPLICATE_FEATURE_SCHEMA = "Entity feature schema is already registered",
	DUPLICATE_ECS_NAME = "Entity schema contains a duplicate ECS name",
	UNKNOWN_PARENT_ARCHETYPE = "Entity schema references an unknown parent archetype",
	UNKNOWN_ARCHETYPE = "Entity archetype is not registered",
	UNKNOWN_FEATURE = "Entity feature is not registered",
	UNKNOWN_COMPONENT = "Entity component is not registered",
	UNKNOWN_TAG = "Entity tag is not registered",
	AMBIGUOUS_ENTITY_KEY = "Entity key is ambiguous without a feature name",
	INVALID_QUERY = "Entity query specification is invalid",
	UNKNOWN_PHASE = "Entity system phase is not registered",
	DUPLICATE_SYSTEM = "Entity system is already registered",
	INVALID_SCHEMA = "Entity feature schema is invalid",
	INVALID_SYSTEM = "Entity system specification is invalid",
	UNKNOWN_ENTITY = "Entity does not exist in the shared world",
	DUPLICATE_INSTANCE_BINDING = "Entity instance binding is already registered",
	INVALID_INSTANCE_BINDING = "Entity instance binding payload is invalid",
	UNKNOWN_INSTANCE_BINDING = "Entity instance binding is not registered",
	UNSUPPORTED_BINDING_ASSET = "Entity instance binding asset could not be resolved",
	INVALID_RUNTIME_MODE = "Entity runtime mode is invalid",
	FEATURE_RUNTIME_NOT_ENABLED = "Entity feature is not enabled for shared runtime execution",
	DUPLICATE_RUNTIME_ENTITY = "Entity is already registered for shared runtime execution",
	UNKNOWN_RUNTIME_ENTITY = "Entity is not registered for shared runtime execution",
	DUPLICATE_SYNC_CONTRIBUTOR = "Entity sync contributor is already registered",
	INVALID_SYNC_CONTRIBUTOR = "Entity sync contributor payload is invalid",
	UNKNOWN_SYNC_CONTRIBUTOR = "Entity sync contributor is not registered",
	DUPLICATE_REPLICATION_SURFACE = "Entity replication surface is already registered",
	INVALID_REPLICATION_SURFACE = "Entity replication surface payload is invalid",
	UNKNOWN_REPLICATION_SURFACE = "Entity replication surface is not registered",
	UNSUPPORTED_REPLICATION_FEATURE = "Entity replication surface is not supported for this feature",
	UNSUPPORTED_AI_RUNTIME_KIND = "Entity AI runtime kind is not supported",
	INVALID_AI_ACTOR_TYPE = "Entity AI actor type payload is invalid",
	DUPLICATE_AI_ACTOR_TYPE = "Entity AI actor type is already registered",
	INVALID_AI_PROFILE = "Entity AI profile resolution is invalid",
	UNKNOWN_AI_ACTOR_TYPE = "Entity AI actor type is not registered",
	INVALID_AI_REGISTRATION = "Entity AI registration payload is invalid",
	DUPLICATE_AI_ENTITY_REGISTRATION = "Entity AI entity is already registered",
	AI_RUNTIME_BRIDGE_UNAVAILABLE = "Entity AI runtime bridge is unavailable",
	MISSING_REQUIRED_AI_ACTOR_TYPE = "EntityContext requires at least one AI actor type before startup",
	OPERATIONAL_PROOF_FAILED = "EntityContext operational proof failed",
})

return Errors
